input:
  path: ../data/tmp/input_eval/rmwaterhouse/
  file: aac2zSGIXr5fjZvJjneWFa8N9jFK-zookeys.110.59530.bioc
  #file: awqipQxjojnzAwukvMo3ZZv9r3KW-zookeys.687.13164.bioc
  extension: json
  format: bioc_json # bioc_json, txt
  type: single # single, multiple

output:
  path: ../data/tmp/output_eval/
  # file: PMC3082967 Use input file name instead
  extension: bioc.json
  format: pubanno_json.tgz # bioc_json, pubanno_json.tgz

tmp:
  path: ../data/tmp/

ner:
  # Base HuggingFace Transformer configs
  model: base_transformer
  version: v1.0.1
  model_path: 2022-11-10-18-38_NER_dmis-lab-biobert-large-cased-v1.1_test_model
  from_local: True
  max_seq_length: 512
  
  # OGER configs
  # model: oger # oger
  # model_path: ""
  # version: v1.0.1
  # settings_path: ../configs/oger_settings.ini
  # from_local: Null
  # max_seq_length: Null

rel_ext:
  model: luke # luke
  version: v1.0.1
  model_path: 2023-03-03-16-04_RE_studio-ousia-luke-large_test_model_ml-512 # from the cloud "studio-ousia/luke-large-finetuned-tacred"
  from_local: True
  prune_mode: sorted # random, sorted, ...
  max_seq_length: 512

nlp:
  type: spacy
  model: en_core_web_sm

context:
  mode: multiple # single, multiple 
  size: 3


models:
  path: ../data/resources/models/

logger:
  level: DEBUG #  CRITICAL, ERROR, WARNING, SUCCESS, INFO, DEBUG, TRACE  