input:
  path: ../data/tmp/input_test/
  file: PMC4714060
  extension: txt
  format: txt # bioc_json, txt
  type: multiple # single, multiple

output:
  path: ../data/tmp/output_test/
  # file: PMC3082967 Use input file name instead
  extension: bioc.json
  format: bioc_json # bioc_json

tmp:
  path: ../data/tmp/

# Named Entity Recognition
ner:
  # Base HuggingFace Transformer configs
  model: base_transformer
  version: v1.0.1
  model_path: 2022-11-10-18-38_NER_dmis-lab-biobert-large-cased-v1.1_test_model
  from_local: True
  max_seq_length: 512
  aggregation_strategy: average #simple, first, average, max
  
  # OGER configs
  # model: oger # oger
  # model_path: ""
  # version: v1.0.1
  # settings_path: ../configs/oger_settings.ini
  # from_local: Null
  # max_seq_length: Null

# Named Entity Normalization
nen:
  #OGER configs
  apply_entity_normalization: True
  model: oger 
  version: v1.0.1
  settings_path: ../configs/oger_settings_nen.ini # Don't apply find value postfilter
  merge_strategy: first

# Relation Extraction
rel_ext:
  model: luke # luke
  version: v1.0.1
  model_path: 2023-04-16-12-48_RE_studio-ousia-luke-large_luke-eval-data-v2_context-size-6_tagged-entities_none_class_balanced_ml-512_lr-0.00_bs-16_ep-2 # from the cloud "studio-ousia/luke-large-finetuned-tacred"
  from_local: True
  prune_mode: random # random, ...
  max_seq_length: 512
  tag_entities: True

nlp:
  type: spacy
  model: en_core_web_sm

context:
  size: 6

models:
  path: ../data/resources/models/

logger:
  level: TRACE #  CRITICAL, ERROR, WARNING, SUCCESS, INFO, DEBUG, TRACE  